defaults:
  # seed for random number generator
  seed: 0
  # training configurations
  train_cfgs:
    # device to use for training, options: cpu, cuda, cuda:0, cuda:0,1, etc.
    device: cpu
    # number of threads for torch
    torch_threads: 16
    # number of vectorized environments
    vector_env_nums: 1
    # number of parallel agent, similar to a3c
    parallel: 1
    # total number of episodes
    total_episodes: 100
  # algorithm configurations
  algo_cfgs:
    # The size of replay buffer (memory)
    size: 10000
    # The size of batch
    batch_size: 64
    # normalize observation
    obs_normalize: False
    # Epsilon for exploration
    epsilon: 1.0
    epsilon_decay: 0.995
    epsilon_min: 0.01
    # The discount factor of GAE
    gamma: 0.99
  # logger configurations
  logger_cfgs:
    # use wandb for logging
    use_wandb: False
    # wandb project name
    wandb_project: omnisafe
    # use tensorboard for logging
    use_tensorboard: True
    # save model frequency
    save_model_freq: 100
    # save logger path
    log_dir: "./runs"
    # save model path
    window_lens: 50
  # model configurations
  model_cfgs:
    # weight initialization mode
    weight_initialization_mode: "kaiming_uniform"
    # actor type
    actor_type: discretizer_mlp
    # linear learning rate decay
    linear_lr_decay: False
    # Configuration of Actor network
    actor:
      # Size of hidden layers
      hidden_sizes: [128, 128]
      # Activation function
      activation: relu
      # The learning rate of Actor network
      lr: 0.001
      # Additional Actor configuration
      actor_cfgs:
        # Number of bins for discretization contineous output
        discrete_actions: 11

